name: Prettier Check

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.jsx'
      - '**/*.tsx'
      - '**/*.json'
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install

      - name: Check code format with Prettier
        run: yarn prettier --check .
